# Auto-generated by Terraform from the OCI Free Tier module.
# Do not edit manually; run `tofu apply -target=local_file.packer_vars` to refresh.

compartment_ocid    = "ocid1.compartment.oc1..aaaaaaaahox2upn7fvv4mhoifgbnshs42xlejatfcinkje26faq7yds3yffq"
availability_domain = "EGzq:UK-LONDON-1-AD-3"
subnet_ocid         = "ocid1.subnet.oc1.uk-london-1.aaaaaaaanwgwt4g7coaxbc4o57hypqh3e4dxoucozy3tqpjez42hfv2zcs2a"
base_image_ocid     = "ocid1.image.oc1.uk-london-1.aaaaaaaaq4yv55lluqgawidkpjkfirusngf6mvqvm23efqbgazlkud3oxu5a"
image_name          = "golden-micro"
access_cfg_file     = "syscode-admin"
shape               = "VM.Standard.E2.1.Micro"
ssh_username        = "ubuntu"
enable_monitoring   = false
