#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Bootstrap OCI Object Storage Backend for OpenTofu State
#
# This script creates and configures an OCI Object Storage bucket for storing
# OpenTofu state files. It uses the free tier (20GB storage).
#
# Prerequisites:
# - OCI CLI configured (~/.oci/config)
# - Appropriate permissions to create buckets
#
# Usage:
#   ./scripts/bootstrap-state-backend.sh
###############################################################################

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if OCI CLI is installed
if ! command -v oci &> /dev/null; then
    log_error "OCI CLI not found. Install it first: brew install oci-cli"
    exit 1
fi

log_info "Reading OCI configuration..."

# Read from OCI config
OCI_CONFIG="${HOME}/.oci/config"
if [[ ! -f "$OCI_CONFIG" ]]; then
    log_error "OCI config not found at $OCI_CONFIG"
    log_error "Run: oci setup config"
    exit 1
fi

# Extract values from OCI config
TENANCY_OCID=$(grep "tenancy=" "$OCI_CONFIG" | head -1 | cut -d'=' -f2)
REGION=$(grep "region=" "$OCI_CONFIG" | head -1 | cut -d'=' -f2)
COMPARTMENT_OCID="${COMPARTMENT_OCID:-$TENANCY_OCID}"

# Bucket configuration
BUCKET_NAME="${STATE_BUCKET_NAME:-tofu-state-oci-free-tier}"
NAMESPACE=$(oci os ns get --query 'data' --raw-output 2>/dev/null || echo "")

if [[ -z "$NAMESPACE" ]]; then
    log_error "Failed to get Object Storage namespace"
    exit 1
fi

log_info "Configuration:"
log_info "  Region: $REGION"
log_info "  Namespace: $NAMESPACE"
log_info "  Bucket: $BUCKET_NAME"
log_info "  Compartment: $COMPARTMENT_OCID"
echo

# Check if bucket already exists
log_info "Checking if bucket exists..."
if oci os bucket get --bucket-name "$BUCKET_NAME" --namespace "$NAMESPACE" &>/dev/null; then
    log_warn "Bucket '$BUCKET_NAME' already exists"
    
    # Enable versioning if not enabled
    log_info "Ensuring versioning is enabled..."
    oci os bucket update \
        --bucket-name "$BUCKET_NAME" \
        --namespace "$NAMESPACE" \
        --versioning Enabled \
        >/dev/null 2>&1 || log_warn "Failed to enable versioning (may already be enabled)"
else
    log_info "Creating bucket '$BUCKET_NAME'..."
    oci os bucket create \
        --compartment-id "$COMPARTMENT_OCID" \
        --name "$BUCKET_NAME" \
        --namespace "$NAMESPACE" \
        --public-access-type NoPublicAccess \
        --versioning Enabled \
        --storage-tier Standard \
        >/dev/null
    
    log_info "Bucket created successfully"
fi

# Generate pre-authenticated request (PAR) for backend authentication
log_info "Generating pre-authenticated request..."

PAR_NAME="tofu-backend-$(date +%Y%m%d)"
PAR_EXPIRY=$(date -u -v+365d +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || date -u -d "+365 days" +"%Y-%m-%dT%H:%M:%SZ")

# Create PAR for state file (read/write)
PAR_URL=$(oci os preauth-request create \
    --bucket-name "$BUCKET_NAME" \
    --namespace "$NAMESPACE" \
    --name "$PAR_NAME" \
    --access-type AnyObjectReadWrite \
    --time-expires "$PAR_EXPIRY" \
    --query 'data."access-uri"' \
    --raw-output 2>/dev/null || echo "")

if [[ -z "$PAR_URL" ]]; then
    log_warn "Failed to create PAR (may already exist)"
    log_info "List existing PARs with: oci os preauth-request list --bucket-name $BUCKET_NAME --namespace $NAMESPACE"
else
    log_info "Pre-authenticated request created (expires in 1 year)"
fi

# Create backend configuration file
BACKEND_CONFIG_FILE="tofu/oci/backend-config.tfvars"
log_info "Creating backend configuration file: $BACKEND_CONFIG_FILE"

cat > "$BACKEND_CONFIG_FILE" <<EOF
# OCI Object Storage Backend Configuration
# Generated by bootstrap-state-backend.sh on $(date)

region              = "$REGION"
namespace           = "$NAMESPACE"
state_bucket_name   = "$BUCKET_NAME"
compartment_ocid    = "$COMPARTMENT_OCID"
EOF

log_info "Backend configuration saved to: $BACKEND_CONFIG_FILE"
echo

log_info "${GREEN}✓${NC} Backend setup complete!"
echo
log_info "Next steps:"
log_info "  1. Edit tofu/oci/backend.tf and uncomment the backend block"
log_info "  2. Run: cd tofu/oci && tofu init -migrate-state"
log_info "  3. Confirm migration when prompted"
echo
log_warn "Note: Pre-authenticated requests expire after 1 year. Regenerate with:"
log_warn "  ./scripts/bootstrap-state-backend.sh"
