#!/usr/bin/env bash
set -euo pipefail

###############################################################################
# Bootstrap OCI Object Storage Backend for OpenTofu State
#
# This script creates and configures an OCI Object Storage bucket for storing
# OpenTofu state files via OCI's S3-compatible API. It uses the free tier
# Object Storage allowance.
#
# Prerequisites:
# - OCI CLI configured (~/.oci/config)
# - Appropriate permissions to create/update buckets
# - OCI Customer Secret Key for S3-compatible backend auth
#
# Usage:
#   ./scripts/bootstrap-state-backend.sh
###############################################################################

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Check if OCI CLI is installed
if ! command -v oci &> /dev/null; then
    log_error "OCI CLI not found. Install it first: brew install oci-cli"
    exit 1
fi

log_info "Reading OCI configuration..."

# Read from OCI config
OCI_CONFIG="${HOME}/.oci/config"
if [[ ! -f "$OCI_CONFIG" ]]; then
    log_error "OCI config not found at $OCI_CONFIG"
    log_error "Run: oci setup config"
    exit 1
fi

# Extract values from OCI config
TENANCY_OCID=$(grep "tenancy=" "$OCI_CONFIG" | head -1 | cut -d'=' -f2)
REGION=$(grep "region=" "$OCI_CONFIG" | head -1 | cut -d'=' -f2)
COMPARTMENT_OCID="${COMPARTMENT_OCID:-$TENANCY_OCID}"

# Bucket configuration
BUCKET_NAME="${STATE_BUCKET_NAME:-tofu-state-oci-free-tier}"
NAMESPACE=$(oci os ns get --query 'data' --raw-output 2>/dev/null || echo "")

if [[ -z "$NAMESPACE" ]]; then
    log_error "Failed to get Object Storage namespace"
    exit 1
fi

log_info "Configuration:"
log_info "  Region: $REGION"
log_info "  Namespace: $NAMESPACE"
log_info "  Bucket: $BUCKET_NAME"
log_info "  Compartment: $COMPARTMENT_OCID"
echo

# Check if bucket already exists
log_info "Checking if bucket exists..."
if oci os bucket get --bucket-name "$BUCKET_NAME" --namespace "$NAMESPACE" &>/dev/null; then
    log_warn "Bucket '$BUCKET_NAME' already exists"

    # Enable versioning if not enabled
    log_info "Ensuring versioning is enabled..."
    oci os bucket update \
        --bucket-name "$BUCKET_NAME" \
        --namespace "$NAMESPACE" \
        --versioning Enabled \
        >/dev/null 2>&1 || log_warn "Failed to enable versioning (may already be enabled)"
else
    log_info "Creating bucket '$BUCKET_NAME'..."
    oci os bucket create \
        --compartment-id "$COMPARTMENT_OCID" \
        --name "$BUCKET_NAME" \
        --namespace "$NAMESPACE" \
        --public-access-type NoPublicAccess \
        --versioning Enabled \
        --storage-tier Standard \
        >/dev/null

    log_info "Bucket created successfully"
fi

# Create backend configuration file
BACKEND_CONFIG_FILE="tofu/oci/backend-config.tfvars"
log_info "Creating backend configuration file: $BACKEND_CONFIG_FILE"

cat > "$BACKEND_CONFIG_FILE" <<EOF
# OCI Object Storage S3-compatible backend example.
# Generated by bootstrap-state-backend.sh on $(date)
#
# Fill access_key/secret_key from an OCI Customer Secret Key in a private file.
# Do not commit real key material.

bucket                      = "$BUCKET_NAME"
key                         = "terraform.tfstate"
region                      = "$REGION"
endpoint                    = "https://$NAMESPACE.compat.objectstorage.$REGION.oraclecloud.com"
use_path_style              = true
skip_region_validation      = true
skip_credentials_validation = true
skip_requesting_account_id  = true
skip_metadata_api_check     = true
use_lockfile                = true

# access_key = "<oci-customer-secret-key-id>"
# secret_key = "<oci-customer-secret-key-secret>"
EOF

log_info "Backend configuration saved to: $BACKEND_CONFIG_FILE"
echo

log_info "${GREEN}✓${NC} Backend setup complete!"
echo
log_info "Next steps:"
log_info "  1. Copy backend-config.tfvars to a private location"
log_info "  2. Add OCI Customer Secret Key access_key/secret_key"
log_info "  3. Run: cd tofu/oci && tofu init -reconfigure -backend-config=/private/path/backend-config.tfvars"
